### ISSUE TITLE
'shared_link_access_denied' error when attempting a download from a shared folder with a password 

### ISSUE THREAD

**Issue by ajstewart** [dropbox/dropbox-sdk-python#174]
I'm having an issue when attempting to download a file from a shared Dropbox folder that is protected with a password.

Doing something very simple like:
```
import dropbox

access_token=<mytoken>
dbx = dropbox.Dropbox(access_token)

download = dbx.sharing_get_shared_link_file_to_file("README.md", <url>, path="/README.md", link_password=<password>)
```
Results in:
```
  File "<path>/dropbox/lib/python3.8/site-packages/dropbox/base.py", line 3543, in sharing_get_shared_link_file_to_file
    r = self.request(
  File "<path>/dropbox/lib/python3.8/site-packages/dropbox/dropbox.py", line 293, in request
    raise ApiError(res.request_id,
dropbox.exceptions.ApiError: ApiError('3fd845590b50c4c62bed5947be962de0', GetSharedLinkFileError('shared_link_access_denied', None))
```

If I ask the owner to remove the password the download completes successfully.

Any help would be greatly appreciated. Thanks.

EDIT: dropbox version 9.4.0.

**Comment by greg-db** [comment]
Thanks for the report! This is a known issue for downloading a file with a password with this method. This is currently open with engineering, but I don't have a timeline for a fix right now. I'll follow up here once I have an update

**Comment by ajstewart** [comment]
Ok thanks for the response.

From googling around looking at the Dropbox forums it seems like this has possibly been an issue since 2018. Considering the password is a feature only for Professional or Business users it's disappointing that this has not yet been fixed.

Unfortunately we're now stuck on what we want to use the the API for until this is resolved.

**Comment by greg-db** [comment]
This issue with calling get_shared_link_file with a password is now fixed and should be working properly.

**Comment by ajstewart** [comment]
Thanks very much, I can confirm it does! 👍

**Comment by asong4211** [comment]
Hey @ajstewart, were you able to get this to work? I called the `dbx.sharing_get_shared_link_file()` function and still receives the same error. My file doesn't even have a password either.
```
dropbox.exceptions.ApiError: ApiError('9880a1c96746fb9a15a26edd', GetSharedLinkFileError('shared_link_access_denied', None))
```

**Comment by greg-db** [comment]
@asong4211 The issue reported here was fixed, and the functionality is working for me currently. Since your link doesn't have a password, it sounds like you're not seeing exactly the same issue anyway.

There are a number of reasons that you might get a `shared_link_access_denied` error from this though, e.g., due to other kinds of access controls on the link. If something isn't working as expected though, please feel free to open [a new issue](https://github.com/dropbox/dropbox-sdk-python/issues), [an API ticket](https://www.dropbox.com/developers/contact), or [a forum thread](https://www.dropboxforum.com/t5/forums/postpage/category-id/101000041A/choose-node/true) with the details.
